info:
  title: SAM
  version: 1.3.0
  contact:
    name: Eniola Osineye
  description: |
    The aim of SAM is to help in small business decisions by utilizing data to drive those decisions.
    ---
          How to use on local host:
          1. Install Python from [Python Official Page](https://www.python.org/).
          2. Open Terminal
          3. Go to your file project
          4. Run in terminal ```pip install streamlit``` 
          5. Run in terminal ```pip install Image``` 
          6. Run in terminal ```pip install pandas```
          7. Run in terminal ```pip install altair```
          8. Run in terminal: ```streamlit run app.py```
          9. Navigate to [localhost:8501](http://localhost:8501/)
    ---
servers:
  - url: https://main-sam-eosineye1.endpoint.ainize.ai/

